version: '3.8'

services:
  my-blog:
    image: devgoraebap/my-blog:${APP_VERSION:-latest}
    container_name: my-blog
    ports:
      - "8004:3000"
    volumes:
      - ./storage:/app/storage
      # github secret 변수를 통해 생성되는 파일 마운트
      - ./.env.production.local:/app/.env.production.local
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    external: true