version: "3.8"
services:
  web:
    image: dev-goraebap:latest
    ports:
      - "8002:80"
    volumes:
      - ./config/master.key:/rails/config/master.key
      - ./storage:/rails/storage
      - ./log:/rails/log
    networks:
      - my-network
    container_name: dev-goraebap

networks:
  my-network:
    name: my-network